# Generated by Django 3.0.6 on 2021-04-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikeymodel',
            options={'verbose_name_plural': 'APIKeys'},
        ),
    ]
